BXR = full(XR'*(f(:)./ps(:).*XR));
BXI = full(XI'*(f(:)./ps(:).*XI));
BYR = full(YR'*(h(:)./ps(:).*YR));
BYI = full(YI'*(h(:)./ps(:).*YI));
B2R = full((VR+YR-pbetachi(:).*XR)'*(g(:)./ps(:).*(VR+YR-pbetachi(:).*XR)));
B2I = full((VI+YI-pbetachi(:).*XI)'*(g(:)./ps(:).*(VI+YI-pbetachi(:).*XI)));
disp([rank(BXR),rank(BXI),rank(B2R),rank(B2I),rank(BYR),rank(BYI)]);
rB2R = zeros(3,3);
figure(4);
subplot(3,3,1);
spy(VR'*(g(:)./ps(:).*VR));
rB2R(1) = rank(full(VR'*(g(:)./ps(:).*VR)));
subplot(3,3,2);
spy(VR'*(g(:)./ps(:).*YR));
rB2R(2) = rank(full(VR'*(g(:)./ps(:).*YR)));
subplot(3,3,3);
spy(VR'*(g(:)./ps(:).*pbetachi(:).*XR));
rB2R(3) = rank(full(VR'*(g(:)./ps(:).*pbetachi(:).*XR)));
subplot(3,3,4);
spy(YR'*(g(:)./ps(:).*VR));
rB2R(4) = rank(full(YR'*(g(:)./ps(:).*VR)));
subplot(3,3,5);
spy(YR'*(g(:)./ps(:).*YR));
rB2R(5) = rank(full(YR'*(g(:)./ps(:).*YR)));
subplot(3,3,6);
spy(YR'*(g(:)./ps(:).*pbetachi(:).*XR));
rB2R(6) = rank(full(YR'*(g(:)./ps(:).*pbetachi(:).*XR)));
subplot(3,3,7);
spy((pbetachi(:).*XR)'*(g(:)./ps(:).*VR));
rB2R(7) = rank(full((pbetachi(:).*XR)'*(g(:)./ps(:).*VR)));
subplot(3,3,8);
spy((pbetachi(:).*XR)'*(g(:)./ps(:).*YR));
rB2R(8) = rank(full((pbetachi(:).*XR)'*(g(:)./ps(:).*YR)));
subplot(3,3,9);
spy((pbetachi(:).*XR)'*(g(:)./ps(:).*pbetachi(:).*XR));
rB2R(9) = rank(full((pbetachi(:).*XR)'*(g(:)./ps(:).*pbetachi(:).*XR)));