figure(1);
subplot(2,4,1);mesh(ps,pchi,a);
subplot(2,4,2);mesh(ps,pchi,b);
subplot(2,4,3);mesh(ps,pchi,c);
subplot(2,4,4);mesh(ps,pchi,d);
subplot(2,4,5);mesh(ps,pchi,e);
subplot(2,4,6);mesh(ps,pchi,f);
subplot(2,4,7);mesh(ps,pchi,g);
subplot(2,4,8);mesh(ps,pchi,h);

figure(2);
subplot(2,4,1);mesh(I1R'*(a(:)./ps(:).*I1R));
subplot(2,4,2);mesh(I2R'*(b(:)./ps(:).*I2R));
subplot(2,4,3);mesh(I3R'*(c(:)./ps(:).*I3R));
subplot(2,4,4);mesh(I4R'*(d(:)./ps(:).*I4R));
subplot(2,4,5);mesh(I5R'*(e(:)./ps(:).*I5R));
subplot(2,4,6);mesh(XR'*(f(:)./ps(:).*XR));
subplot(2,4,7);mesh((VR+YR-pbetachi(:).*XR)'*(g(:)./ps(:).*(VR+YR-pbetachi(:).*XR)));
subplot(2,4,8);mesh(YR'*(h(:)./ps(:).*YR));